# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DownLoad' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

   pod 'LGHMakeViewTools','~>0.0.1'
   pod 'Masonry'
   pod 'SVProgressHUD'

  target 'DownLoadTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DownLoadUITests' do
    # Pods for testing
  end

end
